// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htgsisrvdqycxynxzwft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0Z3Npc3J2ZHF5Y3h5bnh6d2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2OTc4NjYsImV4cCI6MjA1NTI3Mzg2Nn0.YSzNlXBeMjcaLKyBxbCzWipCc3c1WgEMHNIv8buNeQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);